In [1]:
import numpy as np

In [2]:
#make random data
np.random.seed(0)
#L = []
L=[]
for _ in range(10):
    n=np.random.randint(5,100)
    L.append(np.random.randn(n))

In [3]:
#make random data
np.random.seed(0)
#L = []
L=[]
for _ in range(10):
    n=np.random.randint(5,100)
    L.append(np.random.randn(n))
    
X = np.concatenate(L)

In [4]:
def Weighted_Std(x,w,axis=None):
    m1 = np.average(x,weights=w,axis=axis)
    m2 = np.average(x**2,weights=w,axis=axis)
    
    w1 = w.sum()
    w2 = (w**2).sum()
    fac = w1**2/(w1**2-w2)
    return m1,(m2-m1**2)*fac
    

In [12]:
#import RunningStats as RS
import pavey as RS

In [13]:
reload(RS)

<module 'pavey' from '/Users/wpk/Documents/python/pavey/__init__.pyc'>

In [10]:
RS.weighted_var(xM,w)

NameError: name 'xM' is not defined

In [14]:
#running average

In [17]:
t = RS.RunningStats()

In [15]:
for x in L:
    t.PushAveVar(w=len(x), ave=x.mean(), var=x.var(ddof=0))

AttributeError: 'RunningStats' object has no attribute 'PushAveVar'

In [295]:
print t.Mean
print t.Var
print t.Std() 
print t.Std(d=1.) 

print t.VarInMean
print t.VarInVar



-0.0719488920479
1.0099652807
1.00497028847
1.00614363421
0.0145502483371
0.0558025752402


In [303]:
xx=np.random.rand(2,3,4)

In [315]:
xx.ndim

3

In [316]:
np.rollaxis(xx,xx.ndim-1,0).shape


(4, 2, 3)

In [297]:
t = RS.RunningStats()
for x in np.concatenate(L):
    t.PushSingle(x)

In [298]:
print t.Mean
print t.Var
print t.Std() 
print t.Std(d=1.) 

print t.VarInMean
print t.VarInVar



-0.0719488920479
1.0099652807
1.00497028847
1.00614363421
1.01232501267
0.0


In [148]:
t = RS.RunningStats()
for x in L:
    t.PushArray(x)

In [149]:
print t.Mean
print t.Var
print t.Std() 
print t.Std(d=1.) 

print t.VarInMean
print t.VarInVar



-0.0719488920479
1.0099652807
1.00497028847
1.00614363421
0.0145502483371
0.0558025752402


In [154]:
t = RS.RunningStats()
s=1
for i in range(0,10,s):
    x = np.concatenate(L[i:i+s])
    t.PushArray(x)

In [155]:
print t.Mean
print t.Var
print t.Std() 
print t.Std(d=1.) 

print t.VarInMean
print t.VarInVar



-0.0719488920479
1.0099652807
1.00497028847
1.00614363421
0.0145502483371
0.0558025752402


In [123]:
reload(RS)

<module 'RunningStats' from '/Users/wpk/Documents/python/RunningStats/__init__.pyc'>

In [124]:
xx = []
for x in L:
    xx.append([len(x),np.mean(x),np.var(x,ddof=0)])
xx = np.array(xx)    

In [125]:
W = xx[:,0]
M = xx[:,1]
V = xx[:,2]

In [142]:
RS.spliced_stats(ave=M,var=V,weights=W)

(429.0, -0.071948892047883434, 1.0099652807010002)

In [143]:
print RS.weighted_var(M,W)
print RS.weighted_var(V,W)

(-0.07194889204788342, 0.014550248337128882)
(0.99730369240443673, 0.055802575240230058)


In [128]:
xx=[]
s=4
for i in range(0,len(W),s):
    x = RS.spliced_stats(ave=M[i:i+s],var=V[i:i+s],weights=W[i:i+s])
    xx.append(x)
    
xx = np.array(xx)    

In [129]:
xx

array([[  1.69000000e+02,   8.77150681e-03,   9.96312384e-01],
       [  1.22000000e+02,  -1.60496984e-01,   1.10161201e+00],
       [  1.38000000e+02,  -9.25204876e-02,   9.30329759e-01]])

In [130]:
print RS.weighted_var(xx[:,1],xx[:,0])
print RS.weighted_var(xx[:,2],xx[:,0])

(-0.07194889204788342, 0.0074686095823019803)
(1.0050325514072669, 0.0067796312314202167)


In [132]:
t2 = RS.RunningStats()
for x in L:
    t2.PushArray(x)
print t2.Mean - t.Mean
print t2.Var - t.Var
print t2.Std() - t.Std()
print t2.VarInMean - t.VarInMean
print t2.VarInVar - t.VarInVar

0.0
0.0
0.0
0.0
0.0


In [278]:
reload(RS)

<module 'RunningStats' from '/Users/wpk/Documents/python/RunningStats/__init__.py'>

In [279]:
#adding
t0 = RS.RunningStats()
t1 = RS.RunningStats()
for x in L[:5]: t0.PushArray(x)
for x in L[5:]: t1.PushArray(x)

In [280]:
tt = t0 + t1

In [275]:
t.Mean, tt.Mean

(-0.071948892047883434, -0.0064618708575709047)

In [277]:
t.VarInMean, tt.VarInMean

(0.01455024833712888, 0.011745538249986934)

In [194]:
tt = t1

In [209]:
tm = t - t0

In [221]:
10//3

3

In [264]:
L1 = []
n0 = 10
n1 = 5
n2 = 100
shape= (10,2)
for _ in range(n0):
            n = np.random.randint(n1,n2)
            L1.append( np.random.randn( *( shape + (n,) ) ) )

In [266]:
np.concatenate(L1,axis=-1).shape

(10, 2, 484)

In [267]:
np.cov?

In [270]:
rowvar = None
0  or 1

1

In [252]:
X1 = np.hstack(L1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

array([[[ 0.53730336, -0.76570219,  0.55578696, ..., -0.66771272,
          1.68192174, -0.85258585],
        [ 0.02295976, -0.01114561,  0.0114989 , ...,  0.9304085 ,
         -0.1753164 , -1.42191987]],

       [[ 1.99795608, -0.85654931, -1.5415874 , ...,  0.69042902,
          0.79667211, -0.65792609],
        [ 0.96888264,  0.22558166,  1.38914532, ...,  1.4333525 ,
          0.41839801,  0.43554616]],

       [[-0.59922428,  0.03308975, -0.85416126, ...,  0.73035179,
          1.10457847, -1.01482591],
        [-0.60233185,  0.9214084 ,  0.46081448, ...,  0.01879179,
         -0.59377745, -2.01188032]],

       ..., 
       [[-0.12656933, -0.36343778,  0.77905122, ...,  0.44721209,
         -0.61612112,  0.46629004],
        [ 1.71483161, -0.83218603,  0.17233914, ...,  0.41780058,
         -1.24021634,  0.90005424]],

       [[ 1.80224223, -0.2082851 ,  1.57437124, ..., -0.00592741,
          1.36606007,  1.55511403],
        [ 0.61332623, -0.28595915,  1.49691099, ..., -0.46189

In [244]:
x = np.random.randn(4,4,5).reshape(-1,5)

In [251]:
np.cov(x,)

array([[-1.17400109, -0.68756795,  1.27248032,  0.68687883,  1.64219518],
       [-0.54378695,  0.56889809, -0.65665038,  0.83320048, -2.31712931],
       [ 0.39005939,  0.78533769, -1.09745767,  0.21229541,  0.07747478],
       [-0.4338056 , -0.13079258, -0.03621   , -2.05040084,  0.74046968],
       [-0.08090047, -0.76792562,  1.07202237,  0.33554654,  0.6610014 ],
       [-1.70160892, -0.26499288, -1.32275206,  0.32747602,  0.07440437],
       [ 0.0410793 ,  1.2596372 ,  0.89166665,  0.50561711, -0.68341667],
       [-0.87649106, -0.00561466,  1.46656234, -0.72579354, -1.73281749],
       [ 0.69995928,  0.03200428,  0.21128828,  0.08739114,  0.65052474],
       [-0.61872509,  0.08914477,  0.24414862, -0.84468071, -0.90257617],
       [ 0.8167717 ,  0.69196854, -1.25528043,  1.25172295, -0.88174769],
       [ 1.48999457,  0.49109938,  0.09023389, -0.05187748,  1.12758788],
       [ 0.04003532, -1.23398409, -0.73024676, -2.47709741,  0.08630437],
       [ 1.28191919, -0.47039149, -1.0

In [156]:
tt = t0+t1

In [196]:
print tt.Mean-t.Mean
print tt.Var-t.Var
print tt.Std()-t.Std()
print tt.Std(d=1.)-t.Std(d=1.)
print tt.VarInMean - t.VarInMean
print tt.VarInVar - t.VarInVar

0.0
0.0
0.0
0.0
0.0
-1.38777878078e-17


In [164]:
t12 = t - t0

In [169]:
print t12.Mean - t1.Mean
print t12.Var - t1.Var
print t12.Std() - t1.Std()
print t12.VarInMean,t1.VarInMean
print t12.VarInVar,t1.VarInVar

0.0
0.0
0.0
0.00799944126475 0.00799944126475
0.0705222517898 0.0705222517898


In [163]:
t1.Var

1.0047224980557292

In [161]:
tt2.Mean

-0.10929595907176887

In [321]:
#make random data
np.random.seed(0)
#L = []
L=[]
for _ in range(10):
    n=np.random.randint(5,100)
    L.append(np.random.randn(4,n))
X=np.hstack(L)
print [x.shape for x in L]
print X.shape

[(4, 49), (4, 10), (4, 14), (4, 9), (4, 95), (4, 90), (4, 50), (4, 47), (4, 96), (4, 76)]
(4, 536)


In [323]:
X.shape

(4, 536)

In [324]:
L[0].shape

(4, 49)

In [325]:
print np.mean(X,axis=-1)
print np.var(X,axis=-1)
print np.std(X,axis=-1)
print np.std(X,ddof=1)

w = np.array([x.shape[-1] for x in L]).astype(float)
xx = np.array([np.mean(x,axis=-1) for x in L])
print Weighted_Std(xx,w,axis=0)[-1]
xx = np.array([np.var(x,axis=-1) for x in L])
print Weighted_Std(xx,w,axis=0)[-1]

[ 0.05379051 -0.01356595 -0.0374074   0.06129336]
[ 0.99559774  0.92140911  1.04518372  1.0981343 ]
[ 0.99779644  0.95990057  1.02234227  1.04791903]
1.00864129162
[ 0.02932735  0.02264334  0.01821863  0.01933503]
[ 0.04375269  0.05257799  0.0741917   0.05984047]


In [327]:
tL=[]
for i in range(L[0].shape[0]):
    tL.append(RS.RunningStats())
    
for x in L:
    for i in range(L[0].shape[0]):
        tL[i].push_vals(x[i,:])

In [329]:
print [t.mean() for t in tL]
print [t.var() for t in tL]
print [t.std() for t in tL]
print [t.std(1.) for t in tL]


[0.053790506107382501, -0.013565953064206725, -0.037407398631313163, 0.061293357130864583]
[0.99559773569860543, 0.92140911208492871, 1.0451837161038431, 1.0981342988650329]
[0.9977964400109901, 0.95990057406219353, 1.0223422695476516, 1.0479190325903203]
[0.99872852469813123, 0.96079725858659548, 1.0232972835527645, 1.048897938952855]


In [330]:
reload(RS)
tV1 = RS.RunningStatsVec(shape=(4,))
for x in L:
    tV1.push_vals(x)

In [333]:
print tV1.mean()
print tV1.var()
print tV1.std()
print tV1.std(1.)
# print tV1.VarInMean
# print tV1.VarInVar

[ 0.05379051 -0.01356595 -0.0374074   0.06129336]
[ 0.99559774  0.92140911  1.04518372  1.0981343 ]
[ 0.99779644  0.95990057  1.02234227  1.04791903]
[ 0.99872852  0.96079726  1.02329728  1.04889794]


In [334]:
reload(RS)
tV1 = RS.RunningStatsVecCov(l=4)
for x in L:
    tV1.push_vals(x)

In [337]:
print tV1.mean()
print tV1.var()
print tV1.std()
print tV1.std(1.)
# print tV1.VarInMean
# print tV1.VarInVar

[ 0.05379051 -0.01356595 -0.0374074   0.06129336]
[ 0.99559774  0.92140911  1.04518372  1.0981343 ]
[ 0.99779644  0.95990057  1.02234227  1.04791903]
[ 0.99872852  0.96079726  1.02329728  1.04889794]


In [343]:
tV1.cov()

array([[ 0.99559774, -0.0031198 ,  0.07252561,  0.06840879],
       [-0.0031198 ,  0.92140911, -0.01537517,  0.0012748 ],
       [ 0.07252561, -0.01537517,  1.04518372, -0.01670212],
       [ 0.06840879,  0.0012748 , -0.01670212,  1.0981343 ]])

In [342]:
np.cov(X,ddof=0)

array([[ 0.99559774, -0.0031198 ,  0.07252561,  0.06840879],
       [-0.0031198 ,  0.92140911, -0.01537517,  0.0012748 ],
       [ 0.07252561, -0.01537517,  1.04518372, -0.01670212],
       [ 0.06840879,  0.0012748 , -0.01670212,  1.0981343 ]])

In [348]:
tV2 = RS.RunningStatsVecCov(l=4)
for x in L:
    for xx in x.T:
        tV2.push_val(xx)

In [352]:
print tV2.mean()
print tV2.var()
print tV2.std()
print tV2.std(1.)

[ 0.05379051 -0.01356595 -0.0374074   0.06129336]
[ 0.99559774  0.92140911  1.04518372  1.0981343 ]
[ 0.99779644  0.95990057  1.02234227  1.04791903]
[ 0.99872852  0.96079726  1.02329728  1.04889794]


In [353]:
tV2.cov()

array([[ 0.99559774, -0.0031198 ,  0.07252561,  0.06840879],
       [-0.0031198 ,  0.92140911, -0.01537517,  0.0012748 ],
       [ 0.07252561, -0.01537517,  1.04518372, -0.01670212],
       [ 0.06840879,  0.0012748 , -0.01670212,  1.0981343 ]])

In [ ]:
tV2 = RS.Runn

In [928]:
reload(RS)
t0 = RS.RunningStatsVecCov(l=4)
t1 = RS.RunningStatsVecCov(l=4)
for x in L[:5]:
    t0.PushArray(x)
for x in L[5:]:
    t1.PushArray(x)
    
tV1 = t0+t1

In [929]:
print tV1.Mean
print tV1.Var
print tV1.Std()
print tV1.Std(d=1.)
print tV1.VarInMean
print tV1.VarInVar

[ 0.05379051 -0.01356595 -0.0374074   0.06129336]
[ 0.99559774  0.92140911  1.04518372  1.0981343 ]
[ 0.99779644  0.95990057  1.02234227  1.04791903]
[ 0.99872852  0.96079726  1.02329728  1.04889794]
[ 0.02932735  0.02264334  0.01821863  0.01933503]
[ 0.04375269  0.05257799  0.0741917   0.05984047]


In [930]:
tV1.VarInCov

array([[ 0.04375269,  0.02081407,  0.02421034,  0.04802766],
       [ 0.02081407,  0.05257799,  0.01916374,  0.00553009],
       [ 0.02421034,  0.01916374,  0.0741917 ,  0.0415887 ],
       [ 0.04802766,  0.00553009,  0.0415887 ,  0.05984047]])

In [917]:
print np.mean(X,axis=-1)
print np.var(X,axis=-1)
print np.std(X,axis=-1)
print np.std(X,ddof=1)

w = np.array([x.shape[-1] for x in L]).astype(float)
xx = np.array([np.mean(x,axis=-1) for x in L])
print Weighted_Std(xx,w,axis=0)[-1]
xx = np.array([np.var(x,axis=-1) for x in L])
print Weighted_Std(xx,w,axis=0)[-1]

xx = np.array([np.cov(x,ddof=0) for x in L])
print Weighted_Std(xx,w,axis=0)[-1]


[ 0.05379051 -0.01356595 -0.0374074   0.06129336]
[ 0.99559774  0.92140911  1.04518372  1.0981343 ]
[ 0.99779644  0.95990057  1.02234227  1.04791903]
1.00864129162
[ 0.02932735  0.02264334  0.01821863  0.01933503]
[ 0.04375269  0.05257799  0.0741917   0.05984047]
[[ 0.04375269  0.02081407  0.02421034  0.04802766]
 [ 0.02081407  0.05257799  0.01916374  0.00553009]
 [ 0.02421034  0.01916374  0.0741917   0.0415887 ]
 [ 0.04802766  0.00553009  0.0415887   0.05984047]]
