In [ ]:
whos

In [1]:
import pavey as RS
import numpy as np
import random

def build_random_sample(X,samp_axis,min_chunk=4,max_chunk=20,shuffle=True):

    nsamp = X.shape[samp_axis]
    
    idx = np.arange(nsamp)
    if shuffle:
        np.random.shuffle(idx)
    
    
        
    i0=0
    i1=np.random.randint(min_chunk,max_chunk)
    XA = []
    while True:
        XA.append(np.take(X,idx[i0:i1],axis=samp_axis))
        if i1==nsamp:
            break
        i0 = i1
        i1 += np.random.randint(min_chunk,max_chunk)
        i1 = min(nsamp,i1)
        
    return XA
    
    

In [2]:
np.asarray(1.0)

array(1.0)

In [3]:
axis = 0
X = np.random.randn(1000,4,3)
XA = build_random_sample(X,axis)


ave = np.array([x.mean(axis=axis) for x in XA])
var = np.array([x.var(axis=axis) for x in XA])
wt = np.array([x.shape[axis] for x in XA])
cov = np.array([RS.cov_nd(x,axis=axis,ddof=0) for x in XA])

In [4]:
reload(RS)

<module 'pavey' from '/Users/wpk/Documents/python/pavey/__init__.pyc'>

In [5]:
t = RS.RunningStatsVecCov(X.shape[1:])
for i in range(ave.shape[0]):
    t.push_stat(wt[i],ave[i],cov[i])

In [6]:
t.mean()

array([[ 0.00677989, -0.02636552, -0.0089058 ],
       [ 0.07487709, -0.01235777,  0.00091311],
       [ 0.06658902, -0.03502993,  0.00679422],
       [ 0.00930937,  0.00743495,  0.04548843]])

In [7]:
t2 = RS.RunningStatsVecCov.from_stats(wt,ave,cov)

In [8]:
t=RS.RunningStatsVec.from_vals(x=np.random.rand(100))

In [9]:
t

In [10]:
(t + t).var()

array(0.10191879836776073)

In [11]:
np.asarray(t._V/ t._W)

array(0.10191879836776073)

In [12]:
t.mean()[t.weight==0]

array([], dtype=float64)

In [13]:
t1 = RS.RunningStatsList.from_stats_gen(RS.RunningStatsVecCov,wt,ave,cov)

In [14]:
L = []
x = np.arange(2,20,2)
for block_size in x:
    L.append(t1.combine(block_size=block_size).mean_SEM())
L = np.array(L)

In [19]:
t2 = t1.combine(block_size=20)

In [20]:
t2.mean_SEM()

array([[ 0.03666588,  0.04562524,  0.03560439],
       [ 0.02448129,  0.04566161,  0.04394688],
       [ 0.00906217,  0.02937409,  0.02334353],
       [ 0.03505651,  0.0107718 ,  0.02631065]])

In [21]:
t1.combine(block_size=20,min_len=None).mean().std(axis=0)

array([[ 0.06358472,  0.07878053,  0.06150087],
       [ 0.0428485 ,  0.080069  ,  0.07391964],
       [ 0.01526236,  0.05056766,  0.03958681],
       [ 0.05912879,  0.01823762,  0.04580827]])

In [ ]:
t1.combine(block_size=20).mean_SE(weighted=False)

In [ ]:
t1.mean

In [ ]:
t1.combine().mean().std(axis=0)

In [ ]:
#%%timeit -n 1
t0 = RS.RunningStatsVecCov.from_vals(np.random.rand(1000))

In [ ]:
t2 = t1.copy()

In [ ]:
t2.combineA(inplace=True)

In [ ]:
x = np.random.rand(10)

In [ ]:
x.std(ddof=1)

In [ ]:
np.sqrt(RS.weighted_var(x,w=np.ones_like(x)*0.4)[1])

In [ ]:
y=np.concatenate((x,x[:5]))

In [ ]:
wt = np.ones_like(x)
wt[:5] = 2.

In [ ]:
np.std(x,ddof=1)

In [ ]:
np.std(y,ddof=0)

In [ ]:
np.sqrt(RS.weighted_var(x,np.ones_like(x))[1])

In [ ]:
np.sqrt(RS.weighted_var(x,wt,unbiased=False)[1])

In [ ]:
m1 = np.mean(y)
m2 = np.mean((y - m1)**2 )
print m1,m2
N=15
print N/(N-1.)

In [ ]:
np.std(y,ddof=0)

In [ ]:
m1 = np.average(x,weights=wt)
m2 = np.average((x-m1)**2,weights=wt)
print np.sqrt(m2)
print m1,m2
w1 = wt.sum()
w2 = (wt*wt).sum()
print w1**2/(w1**2-w2)

In [ ]:
np.sqrt(RS.weighted_var(x,np.ones_like(x))[1])

In [ ]:
a=t[1]

In [ ]:
a.from_stats

In [ ]:
#%%timeit -n 1
w, a, v, c = RS.spliced_stats(ave=ave, var=var, cov=cov, axis=0, weights=wt)

In [ ]:
#%%timeit -n 1
wb, ab, vb, cb = RS.spliced_stats_block(ave=ave, var=var, cov=cov, axis=0, weights=wt, block_size=2)

In [ ]:
#%%timeit -n 1
L = [RS.RunningStatsVecCov.from_stats(*x) for x in zip(wt,ave,cov)]

In [ ]:
t = RS.RunningStatsList(L)

In [ ]:
t2 = t.combineA()

In [ ]:
#%%timeit -n 1
t2 = t.copy()

In [ ]:
t2.combineA(inplace=True)

In [ ]:
%whos

In [ ]:
t.combineA()

In [ ]:
t2.mean() - ab

In [ ]:
t4 = t2.combine()

In [ ]:
t3 = t.combine(3)

In [ ]:
#%%timeit -n 1
wb, ab, vb, cb = RS.spliced_stats_block(ave=ave, var=var, cov=cov, axis=0, weights=wt, block_size=8)

In [ ]:
#%%timeit
t4 = t2.combine(min_len=1)

In [ ]:
ab.shape

In [ ]:
t8 = t4.combine(min_len=1)

In [ ]:
t8a = t.combine(block_size=8,min_len=1)

In [ ]:
t8a

In [ ]:
t.shape[0]/float(8)

In [ ]:
t4.mean().std(axis=0)

In [ ]:
t4.cov() - cb

In [ ]:
cb - t3.cov()

In [ ]:
len(t2)

In [ ]:
t2.var() - vb

In [ ]:
t2.mean()

In [ ]:
(t[0] + t[0].zero_like()).cov()

In [ ]:
x =t[0:0]

In [ ]:
x._list

In [ ]:
sum(t[0:1],t[0].zero_like()).cov()

In [ ]:
len(t2)

In [ ]:
(a+a.zero_like()).var()

In [ ]:
a.mean()

In [ ]:
b = sum(t[:3])

In [ ]:
t[0].mean(), (0+t[0]).mean()

In [ ]:
(t[0] + t[1] + t[2]).mean()

In [ ]:
a.mean()

In [ ]:
b.mean()

In [ ]:
sum(t._list[1:3],t[0]).mean()

In [ ]:
b = sum(t[:3])

In [ ]:
import itertools

In [ ]:
list(itertools.izip_longest(list('abc'),range(2)))

In [ ]:
len(t[::2]), len(t[1::2])

In [ ]:
t.mean()[0]

In [ ]:
m = np.array([x.mean() for x in t])

In [ ]:
#%%timeit -n 5
L2 = [L[i]+L[i+1] for i in range(0,len(L),2)]

In [ ]:
len(L2)

In [ ]:
t = L[0].__class__((1,2))

In [ ]:
t.shape

In [ ]:
L4 = [a+b for a,b in zip(L2[:-1:2],L2[1::2])]

In [ ]:
#%%timeit -n 10
wb, ab, vb, cb = RS.spliced_stats_block_0(ave=ave, var=var, cov=cov, axis=0, weights=wt, block_size=4,squeeze_block=True)

In [ ]:
m = np.array([x.mean() for x in L4])

In [ ]:
#%%timeit -n 10
wa, aa, va, ca = RS.spliced_stats_block_0(ave=ave, var=var, cov=cov, axis=0, weights=wt, block_size=2,squeeze_block=True)

In [ ]:
#%%timeit -n 10
wb, ab, vb, cb = RS.spliced_stats_block_0(ave=ave, var=var, cov=cov, axis=0, weights=wt, block_size=4,squeeze_block=True)

In [ ]:
#%%timeit -n 10
wc, ac, vc, cc = RS.spliced_stats_block_0(ave=aa, var=va, cov=ca, axis=0, weights=wa, block_size=2,squeeze_block=True)

In [ ]:
np.testing.assert_allclose(ab, ac)
np.testing.assert_allclose(vb, vc)
np.testing.assert_allclose(cb, cc)

In [ ]:
ab.mean(axis=0)

In [ ]:
shape = (1,2)

In [ ]:
shape*2

In [ ]:
np.sqrt(RS.weighted_var(ab,wb,axis=0,axis_sum=0)[-1])

In [ ]:
reload(RS)

In [ ]:
X = np.random.rand(1000)

In [ ]:
w, a, v, c = RS.spliced_stats(ave=X, var=True, cov=True, axis=0, weights=None,squeeze_axis=True)

In [ ]:
np.testing.assert_allclose(X.mean(axis=axis), a)
np.testing.assert_allclose(X.var(axis=axis,ddof=0), v)
np.testing.assert_allclose(RS.cov_nd(X,axis=axis,ddof=0), c)

In [ ]:
w, a, v, c = RS.spliced_stats(ave=ave, var=var, cov=cov, axis=0, weights=wt, squeeze_axis=True, squeeze_block=True,block_size=2)

In [ ]:
a[4]

In [ ]:
cov.shape

In [ ]:
ave2 = ave[:86].reshape(*((2,-1)+ave.shape[1:]))
var2 = var[:86].reshape(*((2,-1)+var.shape[1:]))
cov2 = cov[:86].reshape(*((2,-1)+cov.shape[1:]))

In [ ]:
wt

In [ ]:
w2, a2, v2, c2 = RS.spliced_stats(ave=ave2, var=var2, cov=cov2, axis=0, weights=wt[:2], squeeze_axis=True,
                              squeeze_block=True,block_size=None)

In [ ]:
a

In [ ]:
a - X.mean(axis=0)

In [ ]:
np.squeeze(a,axis=0)

In [ ]:
X.mean(axis=0) 

In [ ]:
def roll_end(x):
    return np.rollaxis(x,0,x.ndim)

In [ ]:
ave = roll_end(ave)
var = roll_end(var)
cov = roll_end(cov)

In [ ]:
w, a, v = RS.spliced_stats(ave=ave,var=var,axis=-1,weights=wt)

In [ ]:
np.squeeze(X.reshape(-1,1).mean(axis=0),axis=-1)

In [ ]:
X = np.random.randn(1000)

In [ ]:
w, a, v, c = RS.spliced_stats(ave=X, var=True,  cov=True, axis=0, weights=None)

In [ ]:
a

In [ ]:
np.squeeze(a,axis=0)

In [ ]:
X.mean() - a, X.var(ddof=0) - v

In [ ]:
ave[...,-1]

In [ ]:
print X.mean(axis=0) - a
print X.var(axis=0,ddof=0) - v

In [ ]:
print RS.cov_nd(X,axis=0,ddof=0) - c

In [ ]:
XB = [x.T for x in XA]

In [ ]:
reload(RS)

In [ ]:
w, a, v, c = RS.spliced_stats(ave=X,var=True,cov=True)

In [ ]:
print X.mean(axis=0) - a

In [ ]:
print X.var(axis=0,ddof=0)
print v

In [ ]:
np.cov(X,rowvar=0,ddof=0) - c

In [ ]:
np.rollaxis(X,0,0)

In [ ]:
xx = np.random.randn(1,2,3,4)

In [ ]:
xr = np.rollaxis(xx,2,4).reshape(-1,3)

In [ ]:
np.cov(xr,ddof=0).reshape((1,2,4)*2)

In [ ]:
reload(RS)

In [ ]:
RS.mycov(xx,axis=-2,ddof=0) #

In [ ]:
np.cov(np.roll(xr,2,4)).reshape(xx.shape[:-1]*2)

In [ ]:

np.rollaxis(X,0,X.ndim).shape